project:
  type: website

website:
  title: "Rencontres R"
  favicon: media/favicon.ico
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Alert** - Site web en construction"
    type: info
    position: below-navbar
  page-footer:
    center:
      - text: "Rencontres R | 2012-2025"
  navbar:
    logo: media/logo_RR_small.png
    left:
    - text: "Accueil"
      href: index.qmd
    - text: "Informations"
      menu:
      - text: "Présentation"
        href: presentation.qmd
      - text: "Comité"
        href: comite.qmd
      - text: "Partenaires"
        href: partenaires.qmd
      - text: "Code de conduite"
        href: coc.qmd
      - text: "Mentions légales"
        href: mentionslegales.qmd 
    - text: "Rencontres annuelles"
      href: rencontres.qmd
    right:
      - text: "Source"
        icon: "git"
        href: https://github.com/Rencontres-R/Rencontres_R.git
      - text: "Contact"
        href: "contact.qmd"

format:
  html:
    toc: true
    theme:
      light: flaty
      dark: darkly
    respect-user-color-scheme: true
